# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: add98f28930b8bd1dc43321b29ca01d40ae81a18dfc65594efa77c33389f8586d9041f4d180def2b33295d3456ca2838c732997a8e775560d944fc3a2b5433ab

test:
  secret_key_base: c48961613349900b4909fdf443d818d61053bb9e3b63a936d6da09a58cb410648d0487b572d686732bcf4c66a4a1761343da1e8d38512550a3d5394545dc47a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
